language: cpp
sudo: required

services:
  - docker

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - pip install --user cpp-coveralls
  - docker pull stivius/xibo-linux

script:
  - docker build --cache-from stivius/xibo-linux .

after_success:
  - docker run -ti --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v ${TRAVIS_BUILD_DIR}/output:/output stivius/xibo-linux
