language: cpp
sudo: required

services:
- docker

env:
  global:
    - CACHE_DIR_XIBO=$HOME/.cache/docker
    - CACHE_FILE_XIBO=$CACHE_DIR_XIBO/xibo.tar.gz
cache:
  directories:
  - $CACHE_DIR_XIBO

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- if [ -f ${CACHE_FILE_XIBO} ]; then gunzip -c ${CACHE_FILE_XIBO} | docker load; fi

install:
- docker build -t xibo-linux .
- mkdir -p $CACHE_DIR_XIBO
- if [ ! -f ${CACHE_FILE_XIBO} ]; then docker save xibo-linux | gzip > ${CACHE_FILE_XIBO}; fi

script:
- docker run -ti --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v ${TRAVIS_BUILD_DIR}/build:/build stivius/xibo-linux

after_success:
- tar czf build.tar.gz ${TRAVIS_BUILD_DIR}/build

deploy:
  provider: releases
  api_key:
    secure: sjJQdCOeNatRsJo4gxwPS2UptCvprRpi6JF2sFCTEX/9e72ZpS8ikNae4J8braZw1gE+Ia+dazgVV6Ry+GAOdz+bNwU2Jv5l0RiV+j69pdJmbk0/lIv5Wp/YEPaS8vSlWmQk0K88CJpBgneiaOD1YXYKiqkmbWnQ1kzNNrZr5nUsZUaXy9T4E+qPP9HVpHbZkc104upJN9AakF//X2vJzMqbMv9Lc/TNCTNqvYTK+wOU6MYbMnfv1GBLzrW9lva4URB9/MZ/GXbNzQlVfKNpggtMLksizzsAEp7wnXEx73jdkCBZPmD72sy4A0gGA0gkj0Jv0GZ4VNDqaNIRB03kEVPxl/3FSBQXJV24FEXJgVhBHseOBu6dHnWj4iyVJ4qpZuqYEl0OBJ/8Hp54EIErIwxiAoDXXCoxuxH4IrXX9XfGeGEsSf8QznEnVQb/cIzHbkLhxS5eB8qQ5JWuC0UUL5bkzsh2fgMC7LL73Eidho13sXz3lFK4i2DIhGJokGpRQandKaino6ebnW4HIhRLOmHJZ47Qg2ih9568VgkD0syvv0cm/shwSG3M3GQwJARUEyFDyoM4LtuhLYaZ8tOTSgtzuYHFbfIau3kkaQuVxVjwztAtgA53xMvb1W5bjJwddWgi/E8lBQlx2up8X3eGSiq7p20eOcHIWZ2pGo2/Yxw=
  file: build.tar.gz
  skip_cleanup: true
  on:
    repo: Stivius/XiboLinuxStack
    tags: true
