name: xibo-player
base: core18
version: 1.8-R3
summary: Xibo Linux Player
description: Xibo for Linux Digital Signage Player
grade: stable
confinement: strict

slots:
  dbus-daemon: # name this whatever you want
    interface: dbus
    bus: session
    name: org.gtkmm.xibo # adjust accordingly

apps:
  xibo-player:
    command: desktop-launch $SNAP/bin/watchdog
    plugs: [gsettings, network, home, unity7, x11, pulseaudio, alsa, screen-inhibit-control, framebuffer, opengl]
    slots: [dbus-daemon]
    environment:
      LD_LIBRARY_PATH: $SNAP/bin/libs/:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/lib/x86_64-linux-gnu/:$SNAP/usr/lib/x86_64-linux-gnu/mesa:$SNAP/usr/lib/x86_64-linux-gnu/mesa-egl

  options:
    command: desktop-launch $SNAP/bin/options
    plugs: [gsettings, network, home, unity7, x11, screen-inhibit-control, framebuffer, opengl]
    slots: [dbus-daemon]
    environment:
      LD_LIBRARY_PATH: $SNAP/bin/libs/:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/lib/x86_64-linux-gnu/:$SNAP/usr/lib/x86_64-linux-gnu/mesa:$SNAP/usr/lib/x86_64-linux-gnu/mesa-egl

parts:
  desktop-gtk3:
    build-packages:
      - build-essential
      - libgtk-3-dev
      - software-properties-common
    make-parameters:
      - FLAVOR=gtk3
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
      - fcitx-frontend-gtk3

  zmq: # Ubuntu 18.04 has outdated ZMQ so we are pulling it from official stable repo
    plugin: nil
    override-pull: |
      sudo sh -c "echo 'deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/xUbuntu_18.04/ /' > /etc/apt/sources.list.d/network:messaging:zeromq:release-stable.list"
      wget -nv https://download.opensuse.org/repositories/network:messaging:zeromq:release-stable/xUbuntu_18.04/Release.key -O Release.key
      sudo apt-key add - < Release.key
      sudo apt-get update
      sudo apt install -y libzmq5

  boost: # Ubuntu 18.04 has outdated boost so we have to build it from source
    source: https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz
    plugin: nil
    override-pull: |
      sudo add-apt-repository ppa:mhier/libboost-latest
      sudo apt-get update
      sudo apt-get install -y libboost1.70
      
  player-sources:
    source: build
    plugin: dump
    prime:
      - bin
      - usr/lib
      - lib
    stage-packages:
      - libzmq5
      - libboost1.70
      - libgstreamer1.0-0
      - gstreamer1.0-gtk3
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-libav
      - gstreamer1.0-alsa
      - gstreamer1.0-gl
      - gstreamer1.0-vaapi
      - gstreamer1.0-pulseaudio
      - libgtkmm-3.0-1v5
      - libcanberra-gtk3-module
      - libwebkitgtk-3.0-0
      - libgpm2 # gstreamer warning
      - libslang2 # gstreamer warning
    after: [zmq, boost, desktop-gtk3] 
